language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"

before_script:
  - composer install --prefer-dist --dev
  - mkdir -pv build/logs

after_script:
  - travis_retry php vendor/bin/php-coveralls
  - ls -la build/logs
