language: php

php:
  - "5.6"
  - "7.1"
  - "7.2"

before_script:
  - composer install --prefer-dist --dev
  - mkdir -pv build/logs

after_script:
  - php vendor/bin/coveralls -v
  - ls -la build/logs

